### ISSUE TITLE
Some syntax highlight missing 

### ISSUE THREAD

**Issue by franktoffel** [xhokir/atom-language-gams#2]
Trying your package I can see that most of the syntax highlight is missing when compared to the regular GAMS IDE.

![image](https://cloud.githubusercontent.com/assets/5269170/16579107/6cf413d6-429e-11e6-8f67-291f26329fe8.png)

Am I missing something in the configuration?

**Comment by serdar-** [comment]
Can you try to use Atom Light UI and synthax themes?

**Comment by franktoffel** [comment]
Thanks for the fast reply. I am afraid the suggested changes do not solve the issue...
![image](https://cloud.githubusercontent.com/assets/5269170/16579645/f640dabe-42a0-11e6-99cc-b5332abc133e.png)

**Comment by serdar-** [comment]
Seems like you have one tab space in front of all the lines. Maybe you can select all lines and press Shift + Tab, then you might see more highlighting.

**Comment by franktoffel** [comment]
Oh my... you are right.
![image](https://cloud.githubusercontent.com/assets/5269170/16579813/c8babf1e-42a1-11e6-9020-e1bc8bf80158.png)
(Atom One light Syntax Theme)

I get confused since GAMS recognized it. Sorry!

**Comment by franktoffel** [comment]
So these are the current differences between GAMS and Atom highlighting. Are these designed or just missing?
![image](https://cloud.githubusercontent.com/assets/5269170/19278807/02b3f6ba-8fdf-11e6-9fb3-20aeb8240bb0.png)

**Comment by serdar-** [comment]
This is just a package that somebody wrote and probably his/her purpose was to highlight some important keywords and characters in GAMS language. Probably this highlighting was sufficient for him/her. If you think that you can improve it, feel free to fork this repository and make changes. Then you can create a pull request. Another solution is to write your own package.

**Comment by xhokir** [comment]
Hi! Sorry for my very late reply. Indeed I made this package only for the keyword I was using, and completely forgot about it. Now that I have a bit more skills in git, i'll try to do best, beginning with accepting pull requests....
